pipeline:
  name: Hello_Harness_Pipeline
  identifier: Hello_Harness_Pipeline
  projectIdentifier: your_project_id
  orgIdentifier: your_org_id
  tags: {}
  stages:
    - stage:
        name: Print_Hello
        identifier: Print_Hello
        description: "Stage to print Hello Harness"
        type: CI
        spec:
          execution:
            steps:
              - step:
                  name: Print Hello Harness
                  identifier: Print_Hello_Harness
                  type: Run
                  spec:
                    shell: Bash
                    command: echo "Hello Harness"
