pipeline:
  name: SamplePipeline
  identifier: SamplePipeline
  projectIdentifier: your_project
  orgIdentifier: your_org
  tags: {}
  stages:
    - stage:
        name: harness_build_testing
        identifier: harness_build_testing
        type: CI  # Added 'type' field
        spec:
          execution:
            steps:
              - step:
                  name: Build
                  identifier: Build
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "Starting the Build Process"
                      npm install
                      npm run build
          infrastructure:
            type: KubernetesDirect  # Modify if using a different infra
            spec:
              connectorRef: your_k8s_connector
              namespace: default
              resources:
                limits:
                  memory: 2Gi
                  cpu: "1"
        failureStrategies:  # Added failure strategies
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Retry
                spec:
                  retryCount: 3
                  retryIntervals: [2s, 5s, 10s]
