name: Your Workflow Name

on:
  workflow_dispatch: # Enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print a success message
        run: echo "✅ Workflow executed successfully!"
