name: Your Workflow Name

on:
  workflow_dispatch: # Enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Example Command with Error
        run: |
          echo "Hello, World!"
          echo "Forcing an error now..."
          ls /non_existent_directory # This will throw an error
          exit 1
