name: Hello World

on: [push] # Triggers the workflow on any push event

jobs:
  hello_world_job:
    runs-on: ubuntu-latest # Specifies the environment in which the job runs

    steps:
      - name: Print Hello World
        run: echo "Hello, World!" # Executes a shell command to print "Hello, World!"
