name: Hello Git

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch: # Allows manual trigger via API

jobs:
  hello-git:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Git
        run: echo "Hello Git"
